# -*- coding: utf-8 -*-
"""google_play_scraper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNOzMaLDooODO4CR4e6paK7o0Q4-Yv5j
"""

pip install google-play-scraper

!pip install pipreqs

from google_play_scraper import app, Sort, reviews_all
import pandas as pd
import time

def scrape_duolingo_reviews():
    # Scrape reviews in batches
    all_reviews = []

    # Scrape multiple batches to get 3000+ reviews
    for _ in range(10):
        result = reviews_all(
            'com.duolingo',
            sleep_milliseconds=1000,
            lang='id',
            country='id',
            sort=Sort.MOST_RELEVANT,
            count=300
        )
        all_reviews.extend(result)
        time.sleep(2)  # Add delay between requests

    # Convert to DataFrame
    df = pd.DataFrame(all_reviews)

    # Remove duplicates
    df = df.drop_duplicates(subset=['reviewId'])

    # Save to CSV
    df.to_csv('duolingo_reviews.csv', index=False)
    print(f"Saved {len(df)} reviews to duolingo_reviews.csv")

if __name__ == "__main__":
    scrape_duolingo_reviews()